Order o--> Promotion

class Order {
      {method} total()
      {method} due()
}
note left: context

abstract class Promotion {
      {abstract} {method} discount()
}
note left: strategy

class FidelityPromo extends Promotion {
      {method} discount()
}

class BulkItemPromo extends Promotion {
      {method} discount()
}

class LargeOrderPromo extends Promotion {
      {method} discount()
}

note bottom of FidelityPromo : concrete strategy
note bottom of BulkItemPromo : concrete strategy
note bottom of LargeOrderPromo : concrete strategy
