Order o--> Promotion

class Order {
      {method} total()
      {method} due()
}

abstract class Promotion {
      {abstract} {method} discount()
}

class FidelityPromo extends Promotion {
      {method} discount()
}

class BulkItemPromo extends Promotion {
      {method} discount()
}

class LargeOrderPromo extends Promotion {
      {method} discount()
}
